[package]
name = "rust_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
reqwest = { version = "0.11.22", features = ["json"] }
futures = "0.3.29"
anyhow = "1.0.75"
url = "2.4.1"
indicatif = "0.17.7"
